### ISSUE TITLE
Lock/unlock biometric authentication factor for a VC

### ISSUE THREAD

**Issue by kneckinator** [idpass/inji#133] opened 2022-03-23 06:19 UTC
Note: This concerns locking and unlocking biometric authentication factors on the MOSIP server side, so that biometric authentication cannot be used by any system.

This issue is **not** related to logging in to the app using biometrics.
-----

It should be possible to lock the biometric authentication factor for a VC from the app.

There are four different authentication factors:
  - bio (assumes lock/unlock of all biometric authentication factors – this is what we will have in the first deliverable)
  - bio-FMR (Fingerprint Minutiae Record – ISO 19794-4)
  - bio-IIR (Iris Image Record – ISO 19794-6)
  - bio-FID (Face Image Data – ISO 19794-5)

The tentative way to access the setting is to open a VC and click the "lock" button. @walidkhouryNL will add input and screens.

As part of locking and unlocking an authentication factor, an OTP has to be provided.

The lock/unlock event should be logged in the app so that it can be displayed.

**Comment by typelogic** [comment] 2022-04-05 05:15
I'm still checking it. So far I tested, it seems to work using `demo` but not `bio` which is what we want.. I'm sending now an inquiry to MOSIP team regarding this.

**Comment by typelogic** [comment] 2022-04-05 06:16
Latest update comments by Rounak: `[@dexter](https://newlogic.slack.com/team/UPQCR8Q65) - auth.types.allowed=demo,otp,bio-Finger,bio-Iris,bio-Face`

**Comment by danicaerediano** [comment] 2022-04-05 06:50
@walidkhouryNL can we have updates on the screens please

**Comment by typelogic** [comment] 2022-04-05 07:25
@kneckinator , as the `bio` is not within the permissible values for `authType`, the closest item in lieu of it, would be the `otp`. Will this be a correct `replacement` for `bio` that is described in this ticket? 

As of now, the `authType` = `otp` is disabled for MOSIP-side Resident configuration. I just confirmed minimum pieces of information for us to proceed on certain things. Hi @danicaerediano , you may commence frontend development of this ticket with regards to its error-handling aspect, as the `authType` = `otp` is currently disabled at the MOSIP side for Resident app. Please coordinate with @walidkhouryNL or @kneckinator  in terms of UI screens.

**Comment by walidkhouryNL** [comment] 2022-04-05 10:38
Hello everyone, 
Here are tentative screens for the lock/unlock flow, 

![Screenshot 2022-04-05 at 12 14 30](https://user-images.githubusercontent.com/68055940/161735881-7cb3dd18-9521-4d29-a88b-b6b9592117c3.png)
![Screenshot 2022-04-05 at 12 14 51](https://user-images.githubusercontent.com/68055940/161735895-bf621179-be37-4d71-b35b-f2cfcc01216c.png)

You can also find a quick prototype [here](https://www.figma.com/proto/vyD5itP6rNNdOGTu9WovoH/%5BFIGMA%5D---MOSIP----Resident-App?page-id=18%3A7&node-id=2708%3A28356&viewport=297%2C48%2C0.19&scaling=scale-down&starting-point-node-id=2708%3A28356&show-proto-sidebar=1)

**Locking a VC**
Open ID (VC) > Tap on the “more option” dropdown button (top right corner) > Tap on “unlock” > Scan biometrics (in this case, fingerprint) > Enter OTP > ID is unlocked

**Unlocking a VC**
Open VC > More options > Lock > ID is locked

Few notes: 
- A newly generated ID is locked by default
- Unlocking an ID doesn’t require authentication (unless I misunderstood)
- The “ID successfully unlocked/locked” notifications should automatically disappear after 2s
- Replaced top right corner actions (edit + lock) with a “more options” dropdown button. I think Jeremi had mentioned we would have “Revoke” and “Delete” as added options in later stages, which I’m accounting for in this design. If we’d rather not have this “more options” button right away, we can leave the two edit + lock buttons as it is for now.

**Comment by kneckinator** [comment] 2022-04-06 01:51
> @kneckinator , as the `bio` is not within the permissible values for `authType`, the closest item in lieu of it, would be the `otp`. Will this be a correct `replacement` for `bio` that is described in this ticket?

I would skip `otp` for now @typelogic

**Comment by typelogic** [comment] 2022-04-07 02:59
I checked in MOSIP 1.2.0 and found the list below what it seems to be the list of permissible values for `auth.types.allowed`:
- bio
- bio-Face
- bio-FACE
- bio-FID
- bio-Finger
- bio-FMR
- bio-Iris
- demo
- FMR
- otp
- pin
- fulladdress

**Comment by typelogic** [comment] 2022-04-13 07:46
## MOSIP API Reference

- https://docs.mosip.io/1.1.5/apis/resident-service-apis#post-resident-v1-req-auth-lock
- https://docs.mosip.io/1.1.5/apis/resident-service-apis#post-resident-v1-req-auth-unlock

## Postman POST Payload Request
1) Firt step is an OTP request:
```
{

    "individualId": "9851941769",
    "individualIdType": "UIN",
    "otpChannel": [
        "EMAIL",
        "PHONE"
    ],

    "transactionID": "1430000006"
}
```

2) `/req/auth-lock` POST payload body
```
{

    "individualId": "9851941769",
    "individualIdType": "UIN",
    "otp": "111111",
    "transactionID": "1430000006",
    "authType": ["bio"]
}
```

3) `/req/auth-unlock` POST payload body
```
{

    "individualId": "9851941769",
    "individualIdType": "UIN",
    "otp": "111111",
    "transactionID": "1430000006",
    "authType": [
        "bio"        
    ],
    "unlockForSeconds": "120"
}
```

## Postman POST Payload Response
Success response for `/req/auth-lock` and `/req/auth-unlock`:
```
{
    "id": "mosip.resident.authunlock",
    "version": "v1",
    "str": null,
    "responsetime": "2022-04-13T07:35:44.735Z",
    "metadata": null,
    "response": {
        "status": null,
        "message": "Notification has been sent to the provided contact detail(s)"
    },
    "errors": null
}
```

Error response for `/req/auth-lock` and `/req/auth-unlock`:
```
{
    "id": "mosip.resident.authlock",
    "version": "v1",
    "str": null,
    "responsetime": "2022-04-13T05:27:02.588Z",
    "metadata": null,
    "response": null,
    "errors": [
        {
            "errorCode": "RES-SER-410",
            "errorMessage": "Invalid Input Parameter- authType"
        }
    ]
}
```

**Closed** 2022-04-25 07:38 UTC

**Comment by jannahadlaon** [comment] 2022-10-04 06:48
Testing was blocked due to server error 

![Screenshot_20221004-113453_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/193752515-3c9bb9e2-a817-4c32-879b-d0af459bbdaf.jpg)

**Comment by jannahadlaon** [comment] 2022-10-05 07:09
MOCK_io.mosip.residentapp-0.4.0-rc3-17-5f7c994-develop-temp-dirty-newlogic_20221003_0914.apk - **Android**
0.4.0 (9.2) - **iOS**

**Resident app build:** 
v0.4.0 R3-17-5f7c994 (android)
v0.4.0 (9.2) -iOS

**MOSIP server**: Mock

Device:
 Samsung Galaxy A23
 iPhone 11
 
`Lock` button is not working when clicked. So as the `Rename` button

**Assign back to dev** 
@pmigueld @danicaerediano @kyanthony 

https://user-images.githubusercontent.com/102940764/194000644-ea36876c-d4eb-4766-89a0-c160e69df192.mp4

**Comment by jannahadlaon** [comment] 2022-10-13 06:57
**Tested on:**
Android - MOCK_io.mosip.residentapp-0.4.0-rc5-newlogic_20221012_1559.apk
iOS - 0.4.0 (10.4)

MOSIP server: Mock

**Devices:**
Samsung Galaxy A23
iPhone 11

**Works as expected on ANDROID**
**FAILED ON iOS** @pmigueld @kyanthony @danicaerediano 

**STEPS**

1. Download UIN 
2. Click on the profile and wait for the green check beside **Valid** to appear
3. Click the kebab menu on the upper right corner
4. Select `Lock`
5. App should request OTP 
6. Enter correct OTP
7. Success toast should display
8. Click the kebab menu on the upper right corner again
9. Select `Unlock`
10. App should request OTP 
11.  Enter correct OTP
12. Success toast should display

**Additional comments/ notes**
- Lock/Unlock Feature does not work if the UIN is not Valid (Status has green check beside Valid in ID profile)
- Improve the success toast message to: **`ID successfully locked`**  -> @danicaerediano 
![Screenshot_20221013-142635_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/195523892-13e99616-5a8b-41e4-82f4-cbcfaad1ce53.jpg)

**Comment by danicaerediano** [comment] 2022-10-14 04:48
@jannahadlaon also Lock/Unlock won't work on QA4, and I assume **iOS - 0.4.0 (10.4)** is using QA4?
